copy all build files to msi

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -220,18 +220,6 @@ jobs:
       with:
         dotnet-version: ${{ env.DOTNET_VERSION }}
     
-    - name: Install WiX Toolset
-      run: |
-        # Download and install WiX Toolset v3.11.2
-        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
-        $wixInstaller = "wix311.exe"
-        Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
-        Start-Process -FilePath $wixInstaller -ArgumentList "/quiet" -Wait
-        Remove-Item $wixInstaller
-        
-        # Add WiX to PATH
-        $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
-        echo "WiX Toolset installed successfully"
     
     - name: Restore dependencies
       run: dotnet restore FPVTracksideCore/FPVTracksideCore.sln
@@ -299,11 +287,48 @@ jobs:
           echo "  $relativePath"
         }
     
-    - name: Create WiX Installer Files
+    - name: Install WiX Toolset
       run: |
-        # Create WiX source file for MSI with proper directory structure
-        echo "Creating WiX installer with proper directory structure..."
+        # Download and install WiX Toolset v3.11.2
+        $wixUrl = "https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe"
+        $wixInstaller = "wix311.exe"
+        Invoke-WebRequest -Uri $wixUrl -OutFile $wixInstaller
+        Start-Process -FilePath $wixInstaller -ArgumentList "/quiet" -Wait
+        Remove-Item $wixInstaller
         
+        # Add WiX to PATH
+        $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
+        echo "WiX Toolset installed successfully"
+
+    - name: Create Simple MSI Installer
+      run: |
+        # Create a simple WiX installer using Heat to auto-generate file list
+        echo "Creating simple MSI installer..."
+        
+        # Add WiX to PATH for this step
+        $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
+        
+        # Use Heat to generate component groups for each directory
+        echo "Generating file lists with Heat..."
+        
+        # Generate main files component
+        heat.exe dir "build\windows-x64" -nologo -sfrag -sreg -suid -scom -dr INSTALLFOLDER -cg MainFiles -var var.SourceDir -gg -out MainFiles.wxs -exclude "data" -exclude "themes" -exclude "sounds" -exclude "img" -exclude "bitmapfonts" -exclude "formats" -exclude "httpfiles" -exclude "patreons" -exclude "pilots" -exclude "ffmpeg"
+        
+        # Generate component groups for each subdirectory if they exist
+        $subdirs = @("data", "themes", "sounds", "img", "bitmapfonts", "formats", "httpfiles", "patreons", "pilots", "ffmpeg")
+        $heatFiles = @("MainFiles.wxs")
+        
+        foreach ($dir in $subdirs) {
+          if (Test-Path "build\windows-x64\$dir") {
+            $componentGroup = "${dir}Files"
+            $dirId = "DIR_$dir"
+            $outputFile = "${dir}Files.wxs"
+            heat.exe dir "build\windows-x64\$dir" -nologo -sfrag -sreg -suid -scom -dr $dirId -cg $componentGroup -var var.SourceDir -gg -out $outputFile
+            $heatFiles += $outputFile
+          }
+        }
+        
+        # Create main WiX file
         echo '<?xml version="1.0" encoding="UTF-8"?>' > FPVTracksideCore.wxs
         echo '<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">' >> FPVTracksideCore.wxs
         echo '  <Product Id="*" Name="FPVTrackside" Language="1033" Version="${{ needs.detect-version.outputs.windows-version }}" Manufacturer="FPV Trackside" UpgradeCode="{12345678-1234-1234-1234-123456789012}">' >> FPVTracksideCore.wxs
@@ -311,36 +336,26 @@ jobs:
         echo '    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />' >> FPVTracksideCore.wxs
         echo '    <MediaTemplate EmbedCab="yes" />' >> FPVTracksideCore.wxs
         echo '    <Feature Id="ProductFeature" Title="FPVTrackside" Level="1">' >> FPVTracksideCore.wxs
-        echo '      <ComponentGroupRef Id="ProductComponents" />' >> FPVTracksideCore.wxs
+        echo '      <ComponentGroupRef Id="MainFiles" />' >> FPVTracksideCore.wxs
         
-        # Only add ComponentGroupRefs for directories that actually exist
-        $allDirs = @("data", "themes", "sounds", "img", "bitmapfonts", "formats", "httpfiles", "patreons", "pilots", "ffmpeg")
-        foreach ($dir in $allDirs) {
+        # Add references for existing subdirectories
+        foreach ($dir in $subdirs) {
           if (Test-Path "build\windows-x64\$dir") {
-            $componentGroupName = "${dir}Components"
-            echo "      <ComponentGroupRef Id=`"$componentGroupName`" />" >> FPVTracksideCore.wxs
+            echo "      <ComponentGroupRef Id=`"${dir}Files`" />" >> FPVTracksideCore.wxs
           }
         }
         
-        echo '      <ComponentGroupRef Id="Shortcuts" />' >> FPVTracksideCore.wxs
         echo '    </Feature>' >> FPVTracksideCore.wxs
         echo '    <UIRef Id="WixUI_Minimal" />' >> FPVTracksideCore.wxs
         echo '    <WixVariable Id="WixUILicenseRtf" Value="license.rtf" />' >> FPVTracksideCore.wxs
-        
-        # Add icon if it exists
-        if (Test-Path "build\windows-x64\icon.ico") {
-          echo '    <Property Id="ARPPRODUCTICON" Value="icon.ico" />' >> FPVTracksideCore.wxs
-          echo '    <Icon Id="icon.ico" SourceFile="build\windows-x64\icon.ico" />' >> FPVTracksideCore.wxs
-        }
-        
         echo '  </Product>' >> FPVTracksideCore.wxs
         echo '  <Fragment>' >> FPVTracksideCore.wxs
         echo '    <Directory Id="TARGETDIR" Name="SourceDir">' >> FPVTracksideCore.wxs
         echo '      <Directory Id="ProgramFilesFolder">' >> FPVTracksideCore.wxs
         echo '        <Directory Id="INSTALLFOLDER" Name="FPVTracksideCore">' >> FPVTracksideCore.wxs
         
-        # Create directory structure for each existing directory
-        foreach ($dir in $allDirs) {
+        # Create directory structure for subdirectories
+        foreach ($dir in $subdirs) {
           if (Test-Path "build\windows-x64\$dir") {
             echo "          <Directory Id=`"DIR_$dir`" Name=`"$dir`" />" >> FPVTracksideCore.wxs
           }
@@ -349,103 +364,18 @@ jobs:
         echo '        </Directory>' >> FPVTracksideCore.wxs
         echo '      </Directory>' >> FPVTracksideCore.wxs
         echo '      <Directory Id="ProgramMenuFolder">' >> FPVTracksideCore.wxs
-        echo '        <Directory Id="ProgramMenuDir" Name="FPVTrackside" />' >> FPVTracksideCore.wxs
+        echo '        <Directory Id="ApplicationProgramsFolder" Name="FPVTrackside" />' >> FPVTracksideCore.wxs
         echo '      </Directory>' >> FPVTracksideCore.wxs
         echo '      <Directory Id="DesktopFolder" Name="Desktop" />' >> FPVTracksideCore.wxs
         echo '    </Directory>' >> FPVTracksideCore.wxs
         echo '  </Fragment>' >> FPVTracksideCore.wxs
-        
-        # Create ProductComponents for main executable and DLLs in root directory
         echo '  <Fragment>' >> FPVTracksideCore.wxs
-        echo '    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">' >> FPVTracksideCore.wxs
-        echo '      <Component Id="FPVTracksideCore.exe" Guid="*">' >> FPVTracksideCore.wxs
-        echo '        <File Id="FPVTracksideCore.exe" Name="FPVTracksideCore.exe" Source="build\windows-x64\FPVTracksideCore.exe" KeyPath="yes" />' >> FPVTracksideCore.wxs
-        echo '      </Component>' >> FPVTracksideCore.wxs
-        
-        # Add main DLLs and dependencies from root directory
-        Get-ChildItem "build\windows-x64\*.dll" | ForEach-Object {
-          $fileName = $_.Name
-          $fileId = "root_" + ($fileName -replace '\.', '_' -replace '-', '_')
-          $componentId = "Component_$fileId"
-          
-          echo "      <Component Id=`"$componentId`" Guid=`"*`">" >> FPVTracksideCore.wxs
-          echo "        <File Id=`"$fileId`" Name=`"$fileName`" Source=`"build\windows-x64\$fileName`" KeyPath=`"yes`" />" >> FPVTracksideCore.wxs
-          echo "      </Component>" >> FPVTracksideCore.wxs
-        }
-        
-        # Add other root-level files (config files, etc.)
-        Get-ChildItem "build\windows-x64\*.*" -Exclude "*.dll", "*.exe" | Where-Object { !$_.PSIsContainer } | ForEach-Object {
-          $fileName = $_.Name
-          $fileId = "root_" + ($fileName -replace '\.', '_' -replace '-', '_' -replace '[^a-zA-Z0-9_]', '_')
-          $componentId = "Component_$fileId"
-          
-          echo "      <Component Id=`"$componentId`" Guid=`"*`">" >> FPVTracksideCore.wxs
-          echo "        <File Id=`"$fileId`" Name=`"$fileName`" Source=`"build\windows-x64\$fileName`" KeyPath=`"yes`" />" >> FPVTracksideCore.wxs
-          echo "      </Component>" >> FPVTracksideCore.wxs
-        }
-        
-        echo '    </ComponentGroup>' >> FPVTracksideCore.wxs
-        echo '  </Fragment>' >> FPVTracksideCore.wxs
-        
-        # Create separate ComponentGroups for each directory
-        $guidCounter = 1
-        $baseGuid = "33333333-3333-3333-3333-3333333333"
-        
-        foreach ($dir in $allDirs) {
-          if (Test-Path "build\windows-x64\$dir") {
-            $guid = $baseGuid + $guidCounter.ToString("D2")
-            $componentGroupName = "${dir}Components"
-            
-            echo "  <Fragment>" >> FPVTracksideCore.wxs
-            echo "    <ComponentGroup Id=`"$componentGroupName`" Directory=`"DIR_$dir`">" >> FPVTracksideCore.wxs
-            echo "      <Component Id=`"Component_$dir`" Guid=`"{$guid}`">" >> FPVTracksideCore.wxs
-            
-            # Add all files in this directory
-            Get-ChildItem "build\windows-x64\$dir" -Recurse -File | ForEach-Object {
-              $relativePath = $_.FullName -replace [regex]::Escape((Get-Location).Path + "\build\windows-x64\$dir\"), ""
-              $fileName = $_.Name
-              $fileId = $dir + "_" + ($relativePath -replace '\\', '_' -replace '\.', '_' -replace '-', '_' -replace '[^a-zA-Z0-9_]', '_')
-              
-              # Ensure File ID doesn't start with a number
-              if ($fileId -match '^[0-9]') { $fileId = "F$fileId" }
-              
-              # For files in subdirectories, we need to create the nested directory structure
-              $subPath = Split-Path $relativePath -Parent
-              if ($subPath -and $subPath -ne ".") {
-                # This file is in a subdirectory - we'll put it directly in the component for now
-                echo "        <File Id=`"$fileId`" Name=`"$fileName`" Source=`"build\windows-x64\$dir\$relativePath`" />" >> FPVTracksideCore.wxs
-              } else {
-                # File is directly in the directory
-                echo "        <File Id=`"$fileId`" Name=`"$fileName`" Source=`"build\windows-x64\$dir\$fileName`" />" >> FPVTracksideCore.wxs
-              }
-            }
-            
-            echo "      </Component>" >> FPVTracksideCore.wxs
-            echo "    </ComponentGroup>" >> FPVTracksideCore.wxs
-            echo "  </Fragment>" >> FPVTracksideCore.wxs
-            
-            $guidCounter++
-          }
-        }
-        
-        # Create shortcuts
-        echo '  <Fragment>' >> FPVTracksideCore.wxs
-        echo '    <ComponentGroup Id="Shortcuts" Directory="INSTALLFOLDER">' >> FPVTracksideCore.wxs
-        
-        # Create shortcuts with conditional icon
-        $iconAttribute = ""
-        if (Test-Path "build\windows-x64\icon.ico") {
-          $iconAttribute = ' Icon="icon.ico" IconIndex="0"'
-        }
-        
-        echo '      <Component Id="StartMenuShortcut" Guid="{AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA}">' >> FPVTracksideCore.wxs
-        echo "        <Shortcut Id=`"StartMenuShortcut`" Name=`"FPVTrackside`" Description=`"FPVTrackside Application`" Target=`"[INSTALLFOLDER]FPVTracksideCore.exe`" WorkingDirectory=`"INSTALLFOLDER`"$iconAttribute Directory=`"ProgramMenuDir`" />" >> FPVTracksideCore.wxs
-        echo '        <RemoveFolder Id="ProgramMenuDir" On="uninstall" Directory="ProgramMenuDir" />' >> FPVTracksideCore.wxs
-        echo '        <RegistryValue Root="HKCU" Key="Software\FPVTrackside" Name="installed" Type="integer" Value="1" KeyPath="yes" />' >> FPVTracksideCore.wxs
-        echo '      </Component>' >> FPVTracksideCore.wxs
-        echo '      <Component Id="DesktopShortcut" Guid="{BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB}">' >> FPVTracksideCore.wxs
-        echo "        <Shortcut Id=`"DesktopShortcut`" Name=`"FPVTrackside`" Description=`"FPVTrackside Application`" Target=`"[INSTALLFOLDER]FPVTracksideCore.exe`" WorkingDirectory=`"INSTALLFOLDER`"$iconAttribute Directory=`"DesktopFolder`" />" >> FPVTracksideCore.wxs
-        echo '        <RegistryValue Root="HKCU" Key="Software\FPVTrackside" Name="desktop_shortcut" Type="integer" Value="1" KeyPath="yes" />' >> FPVTracksideCore.wxs
+        echo '    <ComponentGroup Id="ProductShortcuts" Directory="INSTALLFOLDER">' >> FPVTracksideCore.wxs
+        echo '      <Component Id="ApplicationShortcut" Guid="*">' >> FPVTracksideCore.wxs
+        echo '        <Shortcut Id="ApplicationStartMenuShortcut" Name="FPVTrackside" Description="FPVTrackside Application" Target="[INSTALLFOLDER]FPVTracksideCore.exe" WorkingDirectory="INSTALLFOLDER" Directory="ApplicationProgramsFolder" />' >> FPVTracksideCore.wxs
+        echo '        <Shortcut Id="ApplicationDesktopShortcut" Name="FPVTrackside" Description="FPVTrackside Application" Target="[INSTALLFOLDER]FPVTracksideCore.exe" WorkingDirectory="INSTALLFOLDER" Directory="DesktopFolder" />' >> FPVTracksideCore.wxs
+        echo '        <RemoveFolder Id="CleanUpShortCut" Directory="ApplicationProgramsFolder" On="uninstall" />' >> FPVTracksideCore.wxs
+        echo '        <RegistryValue Root="HKCU" Key="Software\Microsoft\FPVTrackside" Name="installed" Type="integer" Value="1" KeyPath="yes" />' >> FPVTracksideCore.wxs
         echo '      </Component>' >> FPVTracksideCore.wxs
         echo '    </ComponentGroup>' >> FPVTracksideCore.wxs
         echo '  </Fragment>' >> FPVTracksideCore.wxs
@@ -454,35 +384,35 @@ jobs:
         # Create simple license file
         echo '{\rtf1\ansi\deff0 {\fonttbl {\f0 Times New Roman;}}' > license.rtf
         echo '\f0\fs24' >> license.rtf
-        echo '' >> license.rtf
         echo 'FPV Trackside Core License Agreement' >> license.rtf
         echo '' >> license.rtf
         echo 'This software is provided as-is without any warranty. Use at your own risk.' >> license.rtf
         echo '' >> license.rtf
         echo 'Copyright (c) 2024 FPV Trackside' >> license.rtf
         
-        echo "WiX source files created successfully with proper directory structure"
-    
-    - name: Build MSI Installer
-      run: |
-        # Add WiX to PATH for this step
-        $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
-        
-        # Compile WiX source to MSI
+        # Determine MSI name
         if ("${{ needs.detect-version.outputs.is-release-branch }}" -eq "true") {
           $msiName = "FPV-Trackside-Core-Windows-v${{ needs.detect-version.outputs.windows-version }}.msi"
         } else {
           $msiName = "FPV-Trackside-Core-Windows-${{ github.ref_name }}-v${{ needs.detect-version.outputs.windows-version }}.msi"
         }
         
-        # Build the MSI
-        candle.exe -ext WixUIExtension FPVTracksideCore.wxs -out FPVTracksideCore.wixobj
-        if ($LASTEXITCODE -ne 0) {
-          Write-Error "WiX compilation failed"
-          exit 1
+        # Compile all WiX files
+        echo "Compiling WiX files..."
+        $wixObjFiles = @()
+        foreach ($file in $heatFiles + @("FPVTracksideCore.wxs")) {
+          $objFile = $file -replace '\.wxs$', '.wixobj'
+          candle.exe -nologo -dSourceDir="build\windows-x64" $file -out $objFile
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "WiX compilation failed for $file"
+            exit 1
+          }
+          $wixObjFiles += $objFile
         }
         
-        light.exe -ext WixUIExtension FPVTracksideCore.wixobj -out $msiName
+        # Link to create MSI
+        echo "Linking MSI..."
+        light.exe -nologo -ext WixUIExtension $wixObjFiles -out $msiName
         if ($LASTEXITCODE -ne 0) {
           Write-Error "WiX linking failed"
           exit 1
@@ -491,7 +421,8 @@ jobs:
         # Verify MSI was created
         if (Test-Path $msiName) {
           Write-Host "MSI installer created successfully: $msiName"
-          Get-ChildItem $msiName | Select-Object Name, Length
+          $msiInfo = Get-ChildItem $msiName | Select-Object Name, Length
+          Write-Host "File: $($msiInfo.Name), Size: $([math]::Round($msiInfo.Length / 1MB, 2)) MB"
         } else {
           Write-Error "MSI installer was not created"
           exit 1
